export default  [  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"2 - Impulse Calling",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "imp.mp3",
  },  
  {
    title:"3 - Plastic Summer",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"4 - Imaginations",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"5 - Raising Hope",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"6 - The Winter Song.mp3",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },
 ];

