export default  [  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"2 - Impulse Calling",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "imp.mp3",
  },  
  {
    title:"3 - Acid Dreams",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "acid.mp3",
  },  
  {
    title:"4 - Adixia - Need Your Love  ",
    artist: "Remix Taos Elieri",
    cover: "taos.jpeg",
    file: "adixia.mp3",
  },  
  {
    title:"5 - Advanced Echoes",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "advanced.mp3",
  },  
  {
    title:"6 - Against The Odds",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "against.mp3",
  },  
  {
    title:"7 - Around Circles",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "around.mp3",
  },  
  {
    title:"8 - Better Without That",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "better.mp3",
  },  
  {
    title:"9 - Blinded Sunday",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "blinded.mp3",
  },  
  {
    title:"10 - Brain Service",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "brain.mp3",
  },  
  {
    title:"11 - Breaking Bubbles",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "breaking.mp3",
  },  
  {
    title:"12 - Deep Waiting",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "deep.mp3",
  },  
  {
    title:"13 - Delayed Sky",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "delayed.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },
 ];

