export default  [  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"2 - Impulse Calling",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "imp.mp3",
  },  
  {
    title:"3 - Acid Dreams",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "acid.mp3",
  },  
  {
    title:"4 - Adixia - Need Your Love  ",
    artist: "Remix Taos Elieri",
    cover: "taos.jpeg",
    file: "adixia.mp3",
  },  
  {
    title:"5 - Advanced Echoes",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "advanced.mp3",
  },  
  {
    title:"6 - Against The Odds",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "against.mp3",
  },  
  {
    title:"7 - Around Circles",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "around.mp3",
  },  
  {
    title:"8 - Better Without That",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "better.mp3",
  },  
  {
    title:"9 - Blinded Sunday",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "blinded.mp3",
  },  
  {
    title:"10 - Brain Service",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "brain.mp3",
  },  
  {
    title:"11 - Breaking Bubbles",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "breaking.mp3",
  },  
  {
    title:"12 - Deep Waiting",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "deep.mp3",
  },  
  {
    title:"13 - Delayed Sky",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "delayed.mp3",
  },  
  {
    title:"14 - Desired Hand",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "hand.mp3",
  },  
  {
    title:"15 - Dimensions",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "dime.mp3",
  },  
  {
    title:"16 - Distant Garden",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "dist.mp3",
  },  
  {
    title:"17 - Distorted Mirror.",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "mi.mp3",
  },  
  {
    title:"18 - Drawing Rivers",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "dra.mp3",
  },  
  {
    title:"19 - Explosion Pills",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "pill.mp3",
  },  
  {
    title:"20 - Fading Trip",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "fad.mp3",
  },  
  {
    title:"21 - Final Drops",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "drop.mp3",
  },  
  {
    title:"22 - Fishing Field",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "fish.mp3",
  },  
  {
    title:"23 - Fixing Clouds",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "fix.mp3",
  },  
  {
    title:"24 - Folding Situation",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "fold.mp3",
  },  
  {
    title:"25 - Golden Thinking",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "gold.mp3",
  },  
  {
    title:"26 - High Dosed System",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "high.mp3",
  },  
  {
    title:"27 - Illusionary",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "illu.mp3",
  },  
  {
    title:"28 - Imaginations",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "im.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },  
  {
    title:"1 - About The Ways",
    artist: "Taos Elieri",
    cover: "taos.jpeg",
    file: "about.mp3",
  },
 ];

